name: melodica
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1
environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tray_manager: ^0.5.3
  window_manager: ^0.5.2
  logger: ^2.8.0
  ffi: ^2.2.0
  win32: ^6.4.0
  path_provider: ^2.1.6
  path: ^1.9.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/tray.png
    - assets/

assets:
  - assets/images/tray.png
  - assets/
